name: Add DevReward
description: Add issue with the details of the DevReward
title: "[DevReward]: Name of new issue"
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Fill in the details of the DevReward
  - type: input
    id: reward-size
    attributes:
      label: Reward Size in USD
      description: Reward will be paid out in CSPR
      placeholder: Value in USD
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Reward category
      description: Select the category
      options:
        - NFT
        - DeFi
        - SDK
        - DApps
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your idea as good as possible and use the example for orientation.
      placeholder: here is an example
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Please define acceptance criteria as accurate as possible and use the example for orientation.
      placeholder: Here is an example
    validations:
      required: true